export function memoryViewerUserHtml(): string {
  return `<!doctype html>
<html lang="en" data-theme="light">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="theme-color" content="#f7f8fc">
  <link rel="icon" type="image/png" sizes="64x64" href="/memory-viewer/favicon.png">
  <title>MemoraX Code Memory Viewer</title>
  <script>
    const THEME_STORAGE_KEY='memorax-code-memory-viewer-theme',LANGUAGE_STORAGE_KEY='memorax-code-memory-viewer-language';
    function readPreference(key,allowed,fallback){try{const value=localStorage.getItem(key);return allowed.includes(value)?value:fallback}catch{return fallback}}
    function writePreference(key,value){try{localStorage.setItem(key,value)}catch{}}
    let theme=readPreference(THEME_STORAGE_KEY,['light','dark'],'light'),language=readPreference(LANGUAGE_STORAGE_KEY,['zh','en'],'en');
    document.documentElement.dataset.theme=theme;
    document.documentElement.lang=language==='en'?'en':'zh-CN';
    document.querySelector('meta[name="theme-color"]').content=theme==='dark'?'#10121a':'#f7f8fc';
    window.addEventListener('DOMContentLoaded',()=>{
      const E=id=>document.getElementById(id),project=E('project'),clientSelect=E('client-select'),bootstrapUrl=new URL(location.href),params=bootstrapUrl.searchParams;
      if(params.has('token')){bootstrapUrl.searchParams.delete('token');history.replaceState(null,'',bootstrapUrl)}
      const requestedClient=(params.get('client')||'').toLowerCase();
      let selected=params.get('projectId')||'',client=['claude','claude-code','cc'].includes(requestedClient)?'claude-code':requestedClient==='opencode'?'opencode':'codex',controller,lastBody=null,connectionState=null;
      const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
      const COPY={
        zh:{
          pageTitle:'MemoraX Code 记忆概览',productName:'Memory Viewer',clientGroup:'选择客户端',refresh:'刷新记忆活动',languageSwitch:'Switch to English',themeDark:'切换为深色模式',themeLight:'切换为浅色模式',
          connecting:'正在连接',connected:'已连接',disconnected:'连接中断',updated:'· 刚刚更新',
          eyebrow:'记忆概览',heading:'记忆使用情况',intro:'快速了解客户端会话如何使用项目记忆，以及仓库知识是否已经准备就绪。',scopeLabel:'查看范围',projectAria:'选择仓库',allProjects:'全部仓库',summaryAria:'记忆摘要',
          cardTurns:'会话',cardSearch:'搜索',cardAdd:'写入',cardRepo:'仓库记忆',loading:'正在加载',checking:'正在检查',repoLoading:'仓库知识状态',recentActivity:'最近活动',
          empty:'当前范围还没有会话、搜索或写入活动',error:'暂时无法加载记忆活动，请稍后重试。',selectProject:'选择仓库',selectProjectForStatus:'选择仓库后查看状态',noProjects:'暂无可识别仓库',unassignedProject:'未归属仓库',systemActivity:'系统活动',
          turnNote:'轮客户端会话',searchUnit:'次搜索',addUnit:'次写入',processingUnit:'个处理中',unknownUnit:'个数量未知',activityUnit:'条',
          repoStates:{ready:'可用',preparing:'生成中',not_ready:'未就绪',unknown:'未知'},
          reasons:{usable:'仓库知识可以使用',active_job:'正在生成或更新',bundle_missing:'正在生成仓库知识',bundle_missing_idle:'仓库知识尚未初始化',bundle_invalid:'仓库知识需要重新生成',project_unresolved:'无法定位仓库',validator_unavailable:'暂时无法检查'},
          statuses:{completed:'完成',saved:'已保存',skipped:'未写入',processing:'进行中',interrupted:'已中断',failed:'失败',unknown:'数量未知'},
          sources:{client:'客户端会话',assistant:'助手主动',automatic:'系统自动'}
        },
        en:{
          pageTitle:'MemoraX Code Memory Viewer',productName:'Memory Viewer',clientGroup:'Select client',refresh:'Refresh memory activity',languageSwitch:'切换到中文',themeDark:'Switch to dark mode',themeLight:'Switch to light mode',
          connecting:'Connecting',connected:'Connected',disconnected:'Disconnected',updated:'· Updated just now',
          eyebrow:'Memory at a glance',heading:'Memory usage',intro:'See how client sessions use project memory and whether repository knowledge is ready.',scopeLabel:'View scope',projectAria:'Select repository',allProjects:'All repositories',summaryAria:'Memory summary',
          cardTurns:'Turns',cardSearch:'Search',cardAdd:'Add',cardRepo:'Repo Memory',loading:'Loading',checking:'Checking',repoLoading:'Repository knowledge status',recentActivity:'Recent activity',
          empty:'No turn, Search, or Add activity in the current scope',error:'Memory activity is temporarily unavailable. Please try again later.',selectProject:'Select a repository',selectProjectForStatus:'Select a repository to view its status',noProjects:'No repositories found',unassignedProject:'Unassigned repository',systemActivity:'System activity',
          turnNote:'client turns',searchUnit:'searches',addUnit:'adds',processingUnit:'processing',unknownUnit:'with unknown counts',activityUnit:'items',
          repoStates:{ready:'Ready',preparing:'Generating',not_ready:'Not Ready',unknown:'Unknown'},
          reasons:{usable:'Repository knowledge is ready',active_job:'Generating or updating repository knowledge',bundle_missing:'Generating repository knowledge',bundle_missing_idle:'Repository knowledge has not been initialized',bundle_invalid:'Repository knowledge needs to be regenerated',project_unresolved:'Repository could not be resolved',validator_unavailable:'Status is temporarily unavailable'},
          statuses:{completed:'Completed',saved:'Saved',skipped:'No Add',processing:'Processing',interrupted:'Interrupted',failed:'Failed',unknown:'Count unknown'},
          sources:{client:'Client session',assistant:'Assistant initiated',automatic:'Automatic'}
        }
      };
      const icons={turn:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9"><path d="M5 6h14v10H9l-4 3z" stroke-linejoin="round"/></svg>',search:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9"><circle cx="10.5" cy="10.5" r="5.5"/><path d="m15 15 4 4" stroke-linecap="round"/></svg>',add:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9"><path d="M12 7v10M7 12h10" stroke-linecap="round"/></svg>'};
      const copy=()=>COPY[language],locale=()=>language==='en'?'en-US':'zh-CN',number=value=>Number(value||0).toLocaleString(locale()),date=value=>new Intl.DateTimeFormat(locale(),{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(value));
      function endpoint(){const next=new URL('/memory-viewer/api/summary',location.href);next.searchParams.set('client',client);if(selected)next.searchParams.set('projectId',selected);return next.pathname+next.search}
      function syncClient(){clientSelect.value=client}
      function syncStaticCopy(){const current=copy();document.title=current.pageTitle;document.documentElement.lang=language==='en'?'en':'zh-CN';document.querySelectorAll('[data-i18n]').forEach(node=>{const value=current[node.dataset.i18n];if(typeof value==='string')node.textContent=value});document.querySelectorAll('[data-i18n-aria]').forEach(node=>{const value=current[node.dataset.i18nAria];if(typeof value==='string')node.setAttribute('aria-label',value)});document.querySelectorAll('[data-i18n-title]').forEach(node=>{const value=current[node.dataset.i18nTitle];if(typeof value==='string')node.setAttribute('title',value)});E('language-toggle').textContent=language==='zh'?'EN':'中';E('language-toggle').setAttribute('aria-label',current.languageSwitch);E('language-toggle').title=current.languageSwitch;syncThemeButton()}
      function syncThemeButton(){const label=theme==='dark'?copy().themeLight:copy().themeDark;E('theme-toggle').setAttribute('aria-label',label);E('theme-toggle').title=label}
      function setTheme(next,persist=true){theme=next;document.documentElement.dataset.theme=theme;document.querySelector('meta[name="theme-color"]').content=theme==='dark'?'#10121a':'#f7f8fc';if(persist)writePreference(THEME_STORAGE_KEY,theme);syncThemeButton()}
      function setLanguage(next,persist=true){language=next;if(persist)writePreference(LANGUAGE_STORAGE_KEY,language);syncStaticCopy();if(lastBody)render(lastBody);if(connectionState!==null)connection(connectionState)}
      function syncProjects(items){const current=selected;project.innerHTML='<option value="">'+esc(copy().allProjects)+'</option>'+items.map(item=>'<option value="'+esc(item.projectId)+'">'+esc(item.projectLabel)+'</option>').join('');project.value=items.some(item=>item.projectId===current)?current:'';selected=project.value}
      function repoState(items){const current=copy(),target=selected?items.find(item=>item.projectId===selected):items.length===1?items[0]:null,state=target?.repoMemory||{status:'unknown',reason:'project_unresolved'},idleOpenCodeBundle=client==='opencode'&&state.reason==='bundle_missing',displayStatus=state.reason==='bundle_missing'&&!idleOpenCodeBundle?'preparing':state.status,reason=idleOpenCodeBundle?'bundle_missing_idle':state.reason;E('repo-state').className='repo-state';E('repo-dot').className='state-dot '+displayStatus;E('repo-label').textContent=target?(current.repoStates[displayStatus]||current.repoStates.unknown):current.selectProject;E('repo-note').classList.remove('skeleton','loading-copy');E('repo-note').textContent=target?(target.projectLabel+' · '+(current.reasons[reason]||current.reasons.validator_unavailable)):items.length?current.selectProjectForStatus:current.noProjects}
      function memoryCount(value){if(language==='zh')return value+' 条记忆';return value+' '+(value===1?'memory':'memories')}
      function activityTitle(item){if(language==='zh'){if(item.kind==='turn')return item.status==='processing'?'会话进行中':item.status==='interrupted'?'会话已中断':'完成一轮会话';if(item.kind==='search')return item.status==='failed'?'搜索失败':'搜索 · '+memoryCount(item.count??0);if(item.status==='saved')return item.count===null?'写入 · 数量未知':'写入 · '+memoryCount(item.count);if(item.status==='skipped')return '写入 · 没有新记忆';if(item.status==='processing')return '写入处理中';if(item.status==='failed')return '写入失败';return '写入完成 · 数量未知'}if(item.kind==='turn')return item.status==='processing'?'Session in progress':item.status==='interrupted'?'Session interrupted':'Session turn completed';if(item.kind==='search')return item.status==='failed'?'Search failed':'Search · '+memoryCount(item.count??0);if(item.status==='saved')return item.count===null?'Add · Count unknown':'Add · '+memoryCount(item.count);if(item.status==='skipped')return 'Add · No new memory';if(item.status==='processing')return 'Add in progress';if(item.status==='failed')return 'Add failed';return 'Add completed · Count unknown'}
      function metaItem(value){return '<span class="meta-item">'+esc(value)+'</span>'}
      function render(body){lastBody=body;const current=copy(),summary=body.summary||{};E('turns').classList.remove('skeleton');E('turns').textContent=number(summary.turnCount);E('turn-note').classList.remove('skeleton','loading-copy');E('turn-note').textContent=language==='en'&&summary.turnCount===1?'client turn':current.turnNote;E('searched').classList.remove('skeleton');E('searched').textContent=number(summary.searchedMemoryCount);E('search-note').classList.remove('skeleton','loading-copy');E('search-note').textContent=number(summary.searchOperationCount)+' '+(language==='en'&&summary.searchOperationCount===1?'search':current.searchUnit);E('added').classList.remove('skeleton');E('added').textContent=number(summary.addedMemoryCount);E('add-note').classList.remove('skeleton','loading-copy');const addParts=[number(summary.addOperationCount)+' '+(language==='en'&&summary.addOperationCount===1?'add':current.addUnit)];if(summary.processingCount)addParts.push(number(summary.processingCount)+' '+current.processingUnit);if(summary.unknownCount)addParts.push(number(summary.unknownCount)+' '+current.unknownUnit);E('add-note').textContent=addParts.join(' · ');syncProjects(body.projects||[]);repoState(body.projects||[]);const activities=body.activities||[];E('activity-note').textContent=number(activities.length)+' '+(language==='en'&&activities.length===1?'item':current.activityUnit);E('activity').innerHTML=activities.map(item=>'<article class="row"><span class="timeline"><span class="event-icon '+esc(item.kind)+'">'+icons[item.kind]+'</span></span><div class="row-main"><div class="row-title">'+esc(activityTitle(item))+'</div><div class="row-meta">'+metaItem(item.projectLabel||current.unassignedProject)+'<span class="meta-separator"></span>'+metaItem(current.sources[item.source]||current.systemActivity)+'<span class="meta-separator"></span>'+metaItem(date(item.occurredAt))+'</div></div><span class="status '+esc(item.status)+'">'+esc(current.statuses[item.status]||item.status)+'</span></article>').join('');E('empty').hidden=activities.length>0;E('error').hidden=true}
      function connection(ok){connectionState=ok;const current=copy(),pill=E('connection-pill');pill.classList.toggle('offline',!ok);E('connection').textContent=ok?current.connected:current.disconnected;E('connection-time').textContent=ok?current.updated:''}
      async function refresh(){if(controller)controller.abort();const request=new AbortController();controller=request;E('refresh').classList.add('loading');E('refresh').disabled=true;try{const response=await fetch(endpoint(),{signal:request.signal,credentials:'same-origin'});if(!response.ok)throw new Error('HTTP '+response.status);render(await response.json());connection(true)}catch(error){if(error.name==='AbortError')return;connection(false);E('error').hidden=false}finally{if(controller===request){E('refresh').classList.remove('loading');E('refresh').disabled=false}}}
      async function poll(){if(document.visibilityState==='visible')await refresh();setTimeout(poll,10000)}
      clientSelect.onchange=()=>{if(clientSelect.value===client)return;client=clientSelect.value;selected='';syncClient();const next=new URL(location.href);next.searchParams.set('client',client);next.searchParams.delete('projectId');history.replaceState(null,'',next);refresh()};
      project.onchange=()=>{selected=project.value;const next=new URL(location.href);next.searchParams.set('client',client);if(selected)next.searchParams.set('projectId',selected);else next.searchParams.delete('projectId');history.replaceState(null,'',next);refresh()};
      E('language-toggle').onclick=()=>setLanguage(language==='zh'?'en':'zh');
      E('theme-toggle').onclick=()=>setTheme(theme==='light'?'dark':'light');
      E('refresh').onclick=refresh;
      syncClient();
      syncStaticCopy();
      poll();
    });
  </script>
  <style>
    :root{color-scheme:light;--canvas:#f7f8fc;--surface:#fff;--surface-soft:#fafbfe;--ink:#171b27;--muted:#687084;--quiet:#9299aa;--line:#e7e9f1;--line-strong:#d9dce8;--violet:#7156d9;--violet-soft:#f0edff;--cyan:#167c9d;--cyan-soft:#e8f7fb;--green:#168452;--green-soft:#e9f8f0;--amber:#a56818;--amber-soft:#fff4df;--red:#c23b50;--red-soft:#fff0f2;--shadow:0 18px 50px rgba(40,43,65,.07),0 2px 8px rgba(40,43,65,.04);--header-border:rgba(225,227,236,.82);--header-bg:rgba(247,248,252,.82);--control-bg:rgba(255,255,255,.7);--control-bg-strong:#fff;--select-bg:rgba(255,255,255,.88);--card-bg:rgba(255,255,255,.9);--panel-bg:rgba(255,255,255,.83);--product-ink:#464d60;--card-label:#555d70;--section-icon:#6f768a;--row-line:#edeef4;--timeline-line:#e5e7ef;--chip-bg:#f1f2f7;--chip-ink:#747b8d;--empty-icon-bg:#f1f2f6;--empty-icon-ink:#81889a;--skeleton-a:#eef0f5;--skeleton-b:#f7f8fb;--glow-violet:rgba(113,86,217,.07);--glow-cyan:rgba(22,124,157,.055);--active-shadow:0 1px 5px rgba(40,43,65,.11);--hover-shadow:0 22px 58px rgba(40,43,65,.1),0 3px 10px rgba(40,43,65,.05);font-family:Inter,ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI","PingFang SC","Microsoft YaHei",sans-serif}
    [data-theme="dark"]{color-scheme:dark;--canvas:#10121a;--surface:#181b25;--surface-soft:#1e222e;--ink:#f2f3f7;--muted:#adb4c4;--quiet:#858da1;--line:#292e3c;--line-strong:#3a4051;--violet:#a995ff;--violet-soft:rgba(132,108,238,.18);--cyan:#68cbe6;--cyan-soft:rgba(42,153,184,.16);--green:#55cf91;--green-soft:rgba(38,167,101,.16);--amber:#e8b45f;--amber-soft:rgba(195,129,33,.17);--red:#f17a8d;--red-soft:rgba(205,65,87,.16);--shadow:0 18px 50px rgba(0,0,0,.2),0 2px 8px rgba(0,0,0,.14);--header-border:rgba(48,53,69,.88);--header-bg:rgba(16,18,26,.84);--control-bg:rgba(28,32,43,.82);--control-bg-strong:#242936;--select-bg:rgba(27,31,42,.94);--card-bg:rgba(25,28,39,.94);--panel-bg:rgba(24,27,37,.9);--product-ink:#c9ceda;--card-label:#c4cad7;--section-icon:#a6adbd;--row-line:#292e3c;--timeline-line:#303646;--chip-bg:#252a38;--chip-ink:#aeb5c5;--empty-icon-bg:#252a38;--empty-icon-ink:#a6adbd;--skeleton-a:#242936;--skeleton-b:#303646;--glow-violet:rgba(132,108,238,.12);--glow-cyan:rgba(42,153,184,.08);--active-shadow:0 1px 6px rgba(0,0,0,.3);--hover-shadow:0 22px 58px rgba(0,0,0,.26),0 3px 10px rgba(0,0,0,.18)}
    *{box-sizing:border-box}html{background:var(--canvas)}body{margin:0;min-height:100vh;background:radial-gradient(circle at 7% 2%,var(--glow-violet),transparent 25rem),radial-gradient(circle at 96% 28%,var(--glow-cyan),transparent 24rem),var(--canvas);color:var(--ink);-webkit-font-smoothing:antialiased}button,select{font:inherit}button{color:inherit}
    .shell{width:min(1080px,calc(100% - 48px));margin:0 auto}
    header{position:sticky;top:0;z-index:5;border-bottom:1px solid var(--header-border);background:var(--header-bg);backdrop-filter:blur(18px) saturate(150%)}
    .header-inner{height:72px;display:flex;align-items:center}.brand{display:flex;align-items:center;gap:14px;min-width:0}.logo{display:block;height:27px;max-width:168px;transition:filter .18s}.brand-divider{width:1px;height:22px;background:var(--line-strong)}.product-name{font-size:13px;font-weight:650;letter-spacing:.01em;color:var(--product-ink);white-space:nowrap}[data-theme="dark"] .logo{filter:brightness(0) invert(1)}
    .header-actions{margin-left:auto;display:flex;align-items:center;gap:10px}.client-switch{display:flex;padding:3px;border:1px solid var(--line);border-radius:10px;background:var(--control-bg)}.client-select{height:28px;min-width:134px;padding:0 8px;border:0;border-radius:7px;outline:0;background:var(--control-bg-strong);color:var(--ink);font-size:11px;font-weight:680;cursor:pointer}.connection{display:flex;align-items:center;gap:8px;min-height:34px;padding:0 12px;border:1px solid var(--line);border-radius:999px;background:var(--control-bg);color:var(--muted);font-size:11px;font-weight:600}.connection-dot{position:relative;width:7px;height:7px;border-radius:50%;background:var(--green);box-shadow:0 0 0 4px rgba(22,132,82,.1)}.connection.offline{color:var(--red);border-color:color-mix(in srgb,var(--red) 35%,var(--line));background:var(--red-soft)}.connection.offline .connection-dot{background:var(--red);box-shadow:0 0 0 4px rgba(194,59,80,.1)}
    .preference-actions{display:flex;align-items:center;gap:6px}.icon-button{display:grid;width:34px;height:34px;padding:0;place-items:center;border:1px solid var(--line);border-radius:10px;background:var(--control-bg);cursor:pointer;transition:border-color .18s,background-color .18s,transform .18s}.icon-button:hover{border-color:var(--line-strong);background:var(--control-bg-strong);transform:translateY(-1px)}.icon-button:active{transform:translateY(0)}.icon-button svg{width:15px;height:15px}.icon-button.loading svg{animation:spin .8s linear infinite}.language-button{font-size:10px;font-weight:760;letter-spacing:.02em}.theme-sun{display:none}[data-theme="dark"] .theme-sun{display:block}[data-theme="dark"] .theme-moon{display:none}
    main{padding:56px 0 80px}.hero{display:grid;grid-template-columns:minmax(0,1fr) 280px;align-items:end;gap:40px;margin-bottom:28px}.eyebrow{display:flex;align-items:center;gap:8px;margin-bottom:11px;color:var(--violet);font-size:11px;font-weight:760;letter-spacing:.11em;text-transform:uppercase}.eyebrow:before{content:"";width:19px;height:2px;border-radius:2px;background:currentColor}.hero h1{margin:0;font-size:clamp(30px,4vw,42px);font-weight:730;line-height:1.12;letter-spacing:-.04em}.hero p{max-width:620px;margin:13px 0 0;color:var(--muted);font-size:14px;line-height:1.7}
    .scope label{display:block;margin:0 0 8px;color:var(--muted);font-size:11px;font-weight:650}.select-wrap{position:relative}.select-wrap svg{position:absolute;right:13px;top:50%;width:14px;height:14px;pointer-events:none;transform:translateY(-50%);color:var(--quiet)}.scope select{width:100%;height:44px;padding:0 40px 0 13px;appearance:none;border:1px solid var(--line-strong);border-radius:12px;outline:none;background:var(--select-bg);color:var(--ink);font-size:13px;font-weight:570;box-shadow:0 1px 2px rgba(25,27,39,.025);transition:border-color .18s,box-shadow .18s}.scope select:hover{border-color:color-mix(in srgb,var(--violet) 28%,var(--line-strong))}.scope select:focus{border-color:color-mix(in srgb,var(--violet) 60%,transparent);box-shadow:0 0 0 4px color-mix(in srgb,var(--violet) 12%,transparent)}
    .cards{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.card{position:relative;min-height:178px;padding:20px 21px 19px;overflow:hidden;border:1px solid var(--line);border-radius:18px;background:var(--card-bg);box-shadow:var(--shadow);transition:transform .2s,box-shadow .2s}.card:after{content:"";position:absolute;right:-34px;bottom:-48px;width:130px;height:130px;border-radius:50%;opacity:.55}.card:hover{transform:translateY(-2px);box-shadow:var(--hover-shadow)}.card.turn:after{background:radial-gradient(circle,rgba(165,104,24,.12),transparent 68%)}.card.search:after{background:radial-gradient(circle,rgba(113,86,217,.14),transparent 68%)}.card.add:after{background:radial-gradient(circle,rgba(22,124,157,.13),transparent 68%)}.card.repo:after{background:radial-gradient(circle,rgba(22,132,82,.12),transparent 68%)}
    .card-head{position:relative;z-index:1;display:flex;align-items:center;gap:10px}.card-icon{display:grid;width:31px;height:31px;place-items:center;border-radius:10px}.card-icon svg{width:15px;height:15px}.turn .card-icon{background:var(--amber-soft);color:var(--amber)}.search .card-icon{background:var(--violet-soft);color:var(--violet)}.add .card-icon{background:var(--cyan-soft);color:var(--cyan)}.repo .card-icon{background:var(--green-soft);color:var(--green)}.card-label{color:var(--card-label);font-size:12px;font-weight:680}.metric{position:relative;z-index:1;margin:19px 0 4px;font-size:40px;font-weight:730;line-height:1;font-variant-numeric:tabular-nums;letter-spacing:-.045em}.metric-note{position:relative;z-index:1;color:var(--muted);font-size:11px;line-height:1.45}.repo-state{position:relative;z-index:1;display:flex;align-items:center;gap:9px;margin:22px 0 6px;font-size:21px;font-weight:700;letter-spacing:-.025em}.state-dot{width:9px;height:9px;border-radius:50%;background:var(--quiet);box-shadow:0 0 0 4px rgba(146,153,170,.11)}.state-dot.ready{background:var(--green);box-shadow:0 0 0 4px rgba(22,132,82,.1)}.state-dot.preparing{background:var(--amber);box-shadow:0 0 0 4px rgba(165,104,24,.1)}.state-dot.not_ready{background:var(--red);box-shadow:0 0 0 4px rgba(194,59,80,.1)}
    .activity-section{margin-top:32px;border:1px solid var(--line);border-radius:20px;background:var(--panel-bg);box-shadow:0 14px 44px rgba(40,43,65,.045);overflow:hidden}.section-head{display:flex;align-items:center;gap:12px;padding:20px 22px;border-bottom:1px solid var(--line)}.section-title{display:flex;align-items:center;gap:10px}.section-title svg{width:17px;height:17px;color:var(--section-icon)}.section-head h2{margin:0;font-size:15px;font-weight:700;letter-spacing:-.01em}.section-note{margin-left:auto;padding:4px 8px;border-radius:999px;background:var(--chip-bg);color:var(--muted);font-size:10px;font-weight:650;font-variant-numeric:tabular-nums}.activity{padding:4px 22px}.row{position:relative;display:grid;grid-template-columns:34px minmax(0,1fr) auto;align-items:center;gap:13px;min-height:82px;padding:14px 0;border-bottom:1px solid var(--row-line)}.row:last-child{border-bottom:0}.timeline{position:relative;align-self:stretch;display:grid;place-items:center}.timeline:after{content:"";position:absolute;left:50%;top:calc(50% + 17px);bottom:-31px;width:1px;background:var(--timeline-line)}.row:last-child .timeline:after{display:none}.event-icon{position:relative;z-index:1;display:grid;width:30px;height:30px;place-items:center;border:4px solid var(--surface);border-radius:50%;box-shadow:0 0 0 1px var(--line)}.event-icon svg{width:12px;height:12px}.event-icon.turn{background:var(--amber-soft);color:var(--amber)}.event-icon.search{background:var(--violet-soft);color:var(--violet)}.event-icon.add{background:var(--cyan-soft);color:var(--cyan)}.row-main{min-width:0}.row-title{font-size:13px;font-weight:670;line-height:1.4}.row-meta{display:flex;align-items:center;gap:7px;margin-top:6px;color:var(--quiet);font-size:10px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.meta-separator{width:2px;height:2px;flex:0 0 auto;border-radius:50%;background:var(--quiet)}.status{padding:5px 9px;border-radius:999px;background:var(--chip-bg);color:var(--muted);font-size:10px;font-weight:680;white-space:nowrap}.status.failed,.status.interrupted{background:var(--red-soft);color:var(--red)}.status.processing{background:var(--amber-soft);color:var(--amber)}.status.saved{background:var(--green-soft);color:var(--green)}.status.completed{background:var(--violet-soft);color:var(--violet)}.status.skipped{background:var(--chip-bg);color:var(--chip-ink)}
    .empty,.error{margin:22px;padding:36px 20px;border:1px dashed var(--line-strong);border-radius:14px;color:var(--muted);font-size:12px;text-align:center}.empty-icon{display:grid;width:38px;height:38px;margin:0 auto 10px;place-items:center;border-radius:12px;background:var(--empty-icon-bg);color:var(--empty-icon-ink)}.empty-icon svg{width:17px;height:17px}.error{border-color:color-mix(in srgb,var(--red) 35%,var(--line));background:var(--red-soft);color:var(--red)}[hidden]{display:none!important}
    .skeleton{overflow:hidden;color:transparent!important;border-radius:6px;background:linear-gradient(90deg,var(--skeleton-a) 25%,var(--skeleton-b) 50%,var(--skeleton-a) 75%);background-size:200% 100%;animation:shimmer 1.2s infinite}.metric.skeleton{width:70px;height:40px}.repo-state.skeleton{width:110px;height:25px}.loading-copy{width:90px;height:13px;margin-top:7px}
    :focus-visible{outline:2px solid var(--violet);outline-offset:3px}@keyframes spin{to{transform:rotate(360deg)}}@keyframes shimmer{to{background-position:-200% 0}}
    @media(max-width:780px){.shell{width:min(100% - 28px,1080px)}main{padding:38px 0 60px}.hero{grid-template-columns:1fr;gap:24px}.scope{max-width:none}.cards{grid-template-columns:1fr}.card{min-height:150px}.metric{margin-top:15px}.repo-state{margin-top:18px}.activity{padding:3px 16px}.section-head{padding:18px}.row{grid-template-columns:32px minmax(0,1fr);gap:11px}.status{grid-column:2;justify-self:start;margin-top:-7px}.brand-divider,.product-name{display:none}}
    @media(max-width:720px){.header-inner{height:auto;min-height:108px;display:grid;grid-template-columns:minmax(0,1fr) auto;align-content:center;gap:10px 12px;padding:10px 0}.header-actions{display:contents}.client-switch{grid-column:1/-1;grid-row:2}.client-select{width:100%}.connection{display:none}.preference-actions{grid-column:2;grid-row:1;justify-self:end}}
    @media(max-width:440px){.shell{width:calc(100% - 22px)}.logo{height:24px;max-width:145px}.hero h1{font-size:29px}.hero p{font-size:13px}.card{border-radius:16px}.activity-section{border-radius:16px}.row-meta{display:block;white-space:normal;line-height:1.55}.meta-separator{display:none}.meta-item{margin-right:6px}}
    @media(prefers-reduced-motion:reduce){*,*:before,*:after{scroll-behavior:auto!important;animation-duration:.01ms!important;animation-iteration-count:1!important;transition-duration:.01ms!important}}
  </style>
</head>
<body>
  <header><div class="header-inner shell"><div class="brand"><img class="logo" src="/memory-viewer/logo" alt="MemoraX AI"><span class="brand-divider" aria-hidden="true"></span><span class="product-name" data-i18n="productName">Memory Viewer</span></div><div class="header-actions"><div class="client-switch"><select id="client-select" class="client-select" aria-label="Select client" data-i18n-aria="clientGroup"><option value="codex">Codex</option><option value="claude-code">Claude Code</option><option value="opencode">OpenCode</option></select></div><div id="connection-pill" class="connection" role="status"><span class="connection-dot"></span><span id="connection" data-i18n="connecting">Connecting</span><span id="connection-time" class="connection-time"></span></div><div class="preference-actions"><button id="language-toggle" class="icon-button language-button" type="button" aria-label="切换到中文" title="切换到中文">中</button><button id="theme-toggle" class="icon-button" type="button" aria-label="Switch to dark mode" title="Switch to dark mode"><svg class="theme-moon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M20 15.1A8.5 8.5 0 0 1 8.9 4a8.5 8.5 0 1 0 11.1 11.1Z" stroke-linecap="round" stroke-linejoin="round"/></svg><svg class="theme-sun" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="12" cy="12" r="3.5"/><path d="M12 2v2M12 20v2M4.93 4.93l1.42 1.42M17.65 17.65l1.42 1.42M2 12h2M20 12h2M4.93 19.07l1.42-1.42M17.65 6.35l1.42-1.42" stroke-linecap="round"/></svg></button><button id="refresh" class="icon-button" type="button" aria-label="Refresh memory activity" title="Refresh memory activity" data-i18n-aria="refresh" data-i18n-title="refresh"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M20 11a8 8 0 1 0-2.34 5.66M20 4v7h-7" stroke-linecap="round" stroke-linejoin="round"/></svg></button></div></div></div></header>
  <main class="shell">
    <section class="hero">
      <div class="hero-copy"><div class="eyebrow" data-i18n="eyebrow">Memory at a glance</div><h1 data-i18n="heading">Memory usage</h1><p data-i18n="intro">See how client sessions use project memory and whether repository knowledge is ready.</p></div>
      <div class="scope"><label for="project" data-i18n="scopeLabel">View scope</label><div class="select-wrap"><select id="project" aria-label="Select repository" data-i18n-aria="projectAria"><option value="" data-i18n="allProjects">All repositories</option></select><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="m7 9 5 5 5-5" stroke-linecap="round" stroke-linejoin="round"/></svg></div></div>
    </section>
    <section class="cards" aria-label="Memory summary" data-i18n-aria="summaryAria">
      <article class="card turn"><div class="card-head"><span class="card-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M5 6h14v10H9l-4 3z" stroke-linejoin="round"/></svg></span><span class="card-label" data-i18n="cardTurns">Turns</span></div><div id="turns" class="metric skeleton" aria-live="polite">—</div><div id="turn-note" class="metric-note skeleton loading-copy" data-i18n="loading">Loading</div></article>
      <article class="card search"><div class="card-head"><span class="card-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="10.5" cy="10.5" r="5.5"/><path d="m15 15 4 4" stroke-linecap="round"/></svg></span><span class="card-label" data-i18n="cardSearch">Search</span></div><div id="searched" class="metric skeleton" aria-live="polite">—</div><div id="search-note" class="metric-note skeleton loading-copy" data-i18n="loading">Loading</div></article>
      <article class="card add"><div class="card-head"><span class="card-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M12 5v14M5 12h14" stroke-linecap="round"/><circle cx="12" cy="12" r="9"/></svg></span><span class="card-label" data-i18n="cardAdd">Add</span></div><div id="added" class="metric skeleton" aria-live="polite">—</div><div id="add-note" class="metric-note skeleton loading-copy" data-i18n="loading">Loading</div></article>
      <article class="card repo"><div class="card-head"><span class="card-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M4 7.5 12 3l8 4.5v9L12 21l-8-4.5z" stroke-linejoin="round"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span><span class="card-label" data-i18n="cardRepo">Repo Memory</span></div><div id="repo-state" class="repo-state skeleton"><span id="repo-dot" class="state-dot unknown"></span><span id="repo-label" data-i18n="checking">Checking</span></div><div id="repo-note" class="metric-note skeleton loading-copy" data-i18n="repoLoading">Repository knowledge status</div></article>
    </section>
    <section class="activity-section"><div class="section-head"><div class="section-title"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M4 6h16M4 12h16M4 18h10" stroke-linecap="round"/></svg><h2 data-i18n="recentActivity">Recent activity</h2></div><span id="activity-note" class="section-note" data-i18n="loading">Loading</span></div><div id="activity" class="activity" aria-live="polite"></div><div id="empty" class="empty" hidden><span class="empty-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M5 5h14v14H5zM8 9h8M8 13h5" stroke-linecap="round"/></svg></span><span data-i18n="empty">No turn, Search, or Add activity in the current scope</span></div><div id="error" class="error" hidden data-i18n="error">Memory activity is temporarily unavailable. Please try again later.</div></section>
  </main>
</body>
</html>`;
}
